### ISSUE TITLE
postExploit: convert Chrome and Firefox password scripts

### ISSUE THREAD

**Issue by Und3rf10w** [Und3rf10w/Aggressor-scripts#5]
The scripts `Get-ChromePasswords.ps1` and  `Get-FirefoxPasswords.ps1` are too large to be imported through `bpowershell_import()`.

Convert them to be hosted using the `bhost_script()` subroutine and execute that way.
# Tasks
- [x] add `bhost_script()` to`postExploit.cna` (currently in `privesc` branch)
- [x] Convert `Get-ChromePasswords.ps1` to use `bhost_script()`
- [x] Convert `Get-FirefoxPasswords.ps1` to use `bhost_script()`
